### ISSUE TITLE
2018.01.第二周

### ISSUE THREAD

**Issue by kinbei** [kinbei/yjly-zh#22]
2017.01.09
- [ ] BUG #39161::【0.7.4】【bug】【经验副本】组队进入经验副本杀怪数量错误 **必须完成**
```
相关逻辑在 cellapp.scene.copy.team_level_map_copy.lua 文件中的 update_map_copy_state() 方法
```
- [ ] BUG #39219::【0.7.4】【优化】【仙盟】仙盟小红点和提示补充 **必须完成**
- [ ] BUG #39374::【0.7.4】【优化】增加用户类型，不会在排行榜、后台报表出现 **必须完成**
- [ ] BUG #38940::【0.7.4】【功能】【洗炼】装备洗炼功能开发  **必须完成**
```
主要逻辑已做好，缺测试, 主要逻辑在 gw_body_parts_wash.lua
```
