### ISSUE TITLE
2017.12.第一周

### ISSUE THREAD

**Issue by kinbei** [kinbei/yjly-zh#4]
**按列表的顺序进行开发** 

**2017.12.04** 
- [x] 生成crontab文件 #1

**2017.12.05**
- [x] 测试计划任务调度是否正常 #5
- [x] lua编写过滤服务器log错误信息工具 #3 **未完成**

**2017.12.06**
- [x] lua DEMO #2 **未完成**
- [x] 熟读相关文档 #8
- [x] 搭建本地调试环境 #9
- [ ] 画出【玩家登录流程图】 #10

**2017.12.07**
- [x] 验证邮件操作，物品操作流水表
- [x] 验证市场操作，物品操作流水表
- [x] 修改 lua编写过滤服务器log错误信息工具
- [ ] 画出【玩家登录流程图】 #10

**2017.12.08**
- [x] 切换地图测试 #12
- [x] 验证市场操作，物品操作流水表
- [ ] 画出【玩家登录流程图】 #10 **未完成**

**2017.12.09**
- [x] 优化lua过滤服务器log错误信息工具,使其可以支持目录文件名匹配
- [ ] 画出【玩家登录流程图】 #10 **未完成**
